services:
  se-workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: se-deal-workspace
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:./dev.db
    volumes:
      - ./prisma:/app/prisma
      - ./dev.db:/app/dev.db
